### ISSUE TITLE
Script 500-software-distro-specific Failing

### ISSUE THREAD

**Issue by ezirius** [arcolinuxd/arco-awesome#3]
Please have a look at the following errors...

error: failed retrieving file 'hardcode-fixer-git-1:...' from bike.seedhost.eu : The request URL returned error: 404
error: failed retrieving file 'hardcode-fixer-git-1:...' from arcolinux.github.io: Maximum file size exceeded

**Comment by arcolinuxz** [comment]
We updated the package while you were trying to get it.

try again
